services:
  # --- سرویس بک‌اند (جنگو) ---
  backend:
    build:
      context: ./backend  # به داکرفایل داخل پوشه بک‌اند اشاره می‌کند
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"  # بک‌اند روی پورت 8000 اجرا می‌شود
    depends_on:
      - db
    env_file:
      - backend/.env.docker

  # --- سرویس فرانت‌اند (Next.js) ---
  frontend:
    build:
      context: ./frontend # به داکرفایل داخل پوشه فرانت‌اند اشاره می‌کند
    ports:
      - "3000:3000"  # فرانت‌اند روی پورت 3000 اجرا می‌شود
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - frontend/.env.local

  # --- سرویس دیتابیس (PostgreSQL) ---
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - backend/.env.docker
    ports:
      - "5432:5432" # این خط اختیاری است اما برای اتصال مستقیم به دیتابیس خوب است

volumes:
  postgres_data:
